#!/bin/sh

# vnc server xstartup file (~/.vnc/xstartup) for LXDE
#
# The sleeps seem to fix a bug where user input is not registered in vncviewer on client 
#
# Fix to make GNOME work:
export XKL_XMODMAP_DISABLE=1
# hack to allow sudo in vncviewer:
xhost +localhost
autocutsel -fork
sleep 2
# unclear if the x-window-manager is needed:
x-window-manager &
sleep 2
lxterminal &
sleep 2
/usr/bin/lxsession -s LXDE -e LXDE &
